# Generated by Django 4.2.5 on 2023-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='no',
        ),
        migrations.AddField(
            model_name='book',
            name='serial_number',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
